example_project/example_app/urls.py
from django.urls import path

from example_app import views

# Template Tagging
app_name = 'example_app'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('users/', views.users, name = 'users'),
    path('forms/', views.forms_view, name = 'forms'),
    path('signup/', views.signup_form, name = 'signup'),
    path('relative/', views.relative, name = 'relative'),
    path('child/', views.child, name = 'child'),
    path('register/', views.register, name = 'register'),
    path('user_logout/', views.user_logout, name = 'user_logout'),
    path('user_login/', views.user_login, name = 'user_login'),
]

example_project/example_project/urls.py
from django.contrib import admin
from django.urls import path, include
from example_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
]

# the path '' means anything will look at the app
# level urls file to see if there is a direction there
# I can change this to look at different app url
# files depending on the path in the form of 'name/'
# for example to look at second app I can say
# path('second_app/', include('second_app.urls')),
# I can also add a view that is not in urls.py by
# using the form path('name/', views.name, name = 'name')

example_project/example_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):

    top_name = models.CharField(max_length = 264, unique = True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):

    topic = models.ForeignKey(Topic, on_delete = models.PROTECT)
    name = models.CharField(max_length = 264, unique = True)
    url = models.URLField(unique = True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):

    name = models.ForeignKey(Webpage, on_delete = models.PROTECT)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class Userinos(models.Model):

    first_name = models.CharField(max_length = 132)
    last_name = models.CharField(max_length = 132)
    email = models.EmailField(max_length = 254)

    def __str__(self):
        return self.first_name

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete = models.PROTECT)

    # additional
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

example_project/example_app/forms.py
from django import forms
from django.core import validators
from example_app.models import Userinos, UserProfileInfo
from django.contrib.auth.models import User

# CUSTOM VALIDATOR
# def check_for_z(value):
#     if value[0].lower() != 'z':
#         rasie forms.ValidationError('Name does not start with Z')

class FormName(forms.Form):
#    name = forms.CharField(validators = [check_for_z])
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label = 'Enter your email again')
    text = forms.CharField(widget = forms.Textarea)
    botcatcher = forms.CharField(required = False, widget = forms.HiddenInput, validators = [validators.MaxLengthValidator(0)])

    # CLEAN FUNCTION W/O USING BUILT IN
    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError('GOTCHA BOT')

    # CLEAN THE ENTIRE FORM
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError('Emails do not match')

class SignUp(forms.ModelForm):

    class Meta:
        model = Userinos
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

example_project/example_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from example_app.models import Topic, Webpage, AccessRecord, Userinos
from . import forms
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records' : webpages_list}

    return render(request, 'example_app/index.html', context = date_dict)

def users(request):
    user_list = Userinos.objects.order_by('first_name')
    usr_dict = {'users' : user_list}

    return render(request, 'example_app/users.html', context = usr_dict)

def forms_view(request):
    form = forms.FormName()

    if request.method == 'post':
        form = forms.FormName(request.POST)

        if form.is_valid():
            #This code will do something with the data
            print('NAME: ' + form.cleaned_data['name'])
            print('EMAIL: ' + form.cleaned_data['email'])
            print('TEXT: ' + form.cleaned_data['text'])


    return render(request, 'example_app/forms.html', {'form': form})

def signup_form(request):
    sup_form = forms.SignUp()

    if request.method == 'POST':
        sup_form = forms.SignUp(request.POST)

        if sup_form.is_valid():
            sup_form.save()
            return index(request)

        else:
            print('ERROR FORM INVALID')

    return render(request, 'example_app/signup.html', {'sup_form' : sup_form})

def relative(request):
    return render(request, 'example_app/relative_url.html')

def child(request):
    context_dict = {'text' : 'hello world', 'number' : 5280}

    return render(request, 'example_app/child.html', context = context_dict)

def register(request):

    registered = False

    if request.method == "POST":
        user_form = forms.UserForm(data = request.POST)
        profile_form = forms.UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user.form.errors, profile_form.errors)

    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request, 'example_app/registration.html',
                    {'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('example_app:index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')

        else:
            print('someone tried to login and failed')
            print('Username: {} and password {}'.format(username, password))
            return HttpResponse('INVALID LOGIN DETAILS SUPPLIED')

    else:
        return render(request, 'example_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('example_app:index'))

example_project/templates/example_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Base Parent</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'example_app:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
                    <a class="nav-item nav-link" href="{% url 'example_app:register' %}">Register</a>
                    <a class="nav-item nav-link" href="{% url 'example_app:child' %}">Child</a>
                    <a class="nav-item nav-link" href="{% url 'example_app:forms' %}">Forms</a>
                    <a class="nav-item nav-link" href="{% url 'example_app:relative' %}">Relative</a>
                    <a class="nav-item nav-link" href="{% url 'example_app:signup' %}">Signup</a>
                    <a class="nav-item nav-link" href="{% url 'example_app:users' %}">Users</a>

                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'example_app:user_logout' %}">Logout</a>

                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'example_app:user_login' %}">Login</a>

                    {% endif %}

                </div>
            </div>
        </nav>

        <div class="container">

            {% block body_block %}

            <p>This will not be carried over to other files</p>

            {% endblock %}

        </div>

    </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

example_project/templates/example_app/child.html
<!DOCTYPE html>
{% extends "example_app/base.html" %}
{% load my_temps %}

    {% block body_block %}

        <h1>Welcome to Child</h1>
        <h2>This is an example of inheritance</h2>

        <h3>{{ text }}</h3>
        <h3>{{ number }}</h3>

        <h3>{{ text|upper }}</h3>
        <h3>{{ number|add:'99' }}</h3>

        <h3>{{ text|cutter:"hello" }}</h3>

    {% endblock %}

example_project/templates/example_app/forms.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Forms</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"
    </head>
    <body>

        <h1>Fill out the form!</h1>
        <div class="container">
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" name="" value="Submit">
            </form>
        </div>

    </body>
</html>

example_project/templates/example_app/index.html
<!DOCTYPE html>

{% extends "example_app/base.html" %}

    {% block body_block %}

        <body>

            <h1>Hello this is a test page</h1>

            <h2>{{ insert_content }}</h2>

            <h1>Level two MTV Paradigm</h1>

            <h2>Here are the access records:</h2>

            <div class="djangtwo">
                {% if access_records %}
                    <table>
                        <thead>
                            <th>Site Name</th>
                            <th>Date Accessed</th>
                        </thead>


                    {% for acc in access_records %}

                        <tr>
                            <td>{{ acc.name }}</td>
                            <td>{{ acc.date }}</td>
                        </tr>

                    {% endfor %}

                    </table>

                {% else %}

                    <p>NO ACCESS RECORDS FOUND</p>

                {% endif %}
            </div>

        </body>

    {% endblock %}

</html>

example_project/templates/example_app/login.html
<!DOCTYPE html>
{% extends 'example_app/base.html' %}
{% block body_block %}

<div class="jumbotron">

    <h1>Please Login</h1>

    <form action="{% url 'example_app:user_login' %}" method="post">

        {% csrf_token %}

        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" name="" value="Login">

    </form>

</div>

{% endblock %}

example_project/templates/example_app/registration.html
<!DOCTYPE html>
{% extends "example_app/base.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">

    {% if registered %}

        <h1>Thank you for registering!</h1>

    {% else %}

        <h1>Register Here!</h1>
        <h3>Fill out the form below:</h3>

        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">

        </form>


    {% endif %}

</div>

{% endblock %}

example_project/templates/example_app/relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>This is the Realative URL Page</h1>

        <a href="{% url 'example_app:users' %}">Users</a>

        <a href="{% url 'admin:index' %}">Admin</a>

        <a href="{% url 'example_app:index' %}">Home</a>

    </body>
</html>

example_project/templates/example_app/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Sign Up</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>

        <div class="container">
            <h1>Sign Up Here</h1>
            <form method="post">
                {{ sup_form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>



        </div>

    </body>
</html>

example_project/templates/example_app/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Users</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>

        <h1>Here are your users:</h1>

        <div class="djanguser">

            {% if users %}
                <ol>

                {% for person in users %}

                    <li>User Info</li>
                    <ul>
                        <li>First Name: {{ person.first_name }}</li>
                        <li>Last Name: {{ person.last_name }}</li>
                        <li>Email: {{ person.email }}</li>
                    </ul>

                {% endfor %}
                </ol>

            {% else %}

                <p>NO USER INFO FOUND</p>

            {% endif %}

        </div>

    </body>
</html>